# Generated by Django 4.2.10 on 2024-08-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_content_post_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='memo',
            new_name='content',
        ),
    ]
